const express = require('express')
const router = express.Router()

const exercicio1_router = require('./exercicioUm.js')
const exercicio2_router = require('./exercicio2.js')
const exercicio3_router = require('./exercicio3.js')
const exercicio4_router = require('./exercicio4.js')
const exercicio5_router = require('./exercicio5.js')
const exercicio6_router = require('./exercicio6.js')
const exercicio7_router = require('./exercicio7.js')
const exercicio8_router = require('./exercicio8.js')
const exercicio9_router = require('./exercicio9.js')
const exercicio10_router = require('./exercicio10.js')

router.use('/exercicio', exercicio1_router)
router.use('/exercicio', exercicio2_router)
router.use('/exercicio', exercicio3_router)
router.use('/exercicio', exercicio4_router)
router.use('/exercicio', exercicio5_router)
router.use('/exercicio', exercicio6_router)
router.use('/exercicio', exercicio7_router)
router.use('/exercicio', exercicio8_router)
router.use('/exercicio', exercicio9_router)
router.use('/exercicio', exercicio10_router)

module.exports = router